name: 'tweede_kamer'
version: '1.0.0'

profile: 'process'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  process:
    +materialized: view
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    mart:
      +schema: mart
      +materialized: table
