[project]
name = "process"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt>=1.0.0.40.6",
    "dbt-core>=1.10.11",
    "dbt-postgres>=1.9.1",
]
